### PR TITLE
People directory web part: added callout with user information

### PR DESCRIPTION
**Pull request by rfjschouten**
#### Category
- [ ] Bug Fix
- [x] New Feature
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Added a callout to the people directory web part. Each person now has a button to open a callout with more info about the user (name, email, phone, mobile, skills, past projects). Solution shows how to use the Fabric UI React Callout component. The information within the Callout is created in a separate component. The component can be easily be adjusted in order to display other information.

screen_shot_2018-08-30_at_09_46_54

### CODE REVIEW

**Comment by raymondlittle100** [comment]
Great addition. To take it a step further it would be good to include line manager details to see who they report to or employees they manage

**Comment by VesaJuvonen** [comment]
Excellent stuff @rfjschouten, appreciated.

**Comment by elpinto007** [comment]
Great stuff! I was looking at something like this. Has someone been able to integrate the Person card from the Modern UI so when you hover over a person result, it can pop open like how the person card does?

**Comment by eschrader** [comment]
Nice! Note, it does not display info for B2B users. Also, if your tenant has external sharing all of those users appear as well.
Is there an easy way to default to the Search box?

**Comment by elpinto007** [comment]
I tried to create a standalone solution for just the People Directory, but I cannot get the MS-Icons to work for some reason. Is there any potential dependency I might be missing out for the icons to be deployed? 
2019-06-19 12_57_31-package json - spfx-starter-wp-people-directory-2 - Visual Studio Code

**Comment by rfjschouten** [comment]
@elpinto007 Check this blogpost about changes with the icons since SPFx version 1.8.2:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#usage-of-the-office-ui-fabric-icons-in-spfx-components

**Comment by elpinto007** [comment]
> @elpinto007 Check this blogpost about changes with the icons since SPFx version 1.8.2:
> https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#usage-of-the-office-ui-fabric-icons-in-spfx-components

Thank you sir! That definitely helped me and now I have the icons showing up as expected. 
I am creating a stand-alone deploying for the Employee Directory, so if anyone is interested in just the Employee Directory, I can upload the current version to my Github.

**Comment by SolidCactus** [comment]
@elpinto007 - I would love to have a look at your current version if you wouldn't mind chucking it into GitHub?

**Comment by dhiru08484** [comment]
> > @elpinto007 Check this blogpost about changes with the icons since SPFx version 1.8.2:
> > https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#usage-of-the-office-ui-fabric-icons-in-spfx-components
> 
> Thank you sir! That definitely helped me and now I have the icons showing up as expected.
> I am creating a stand-alone deploying for the Employee Directory, so if anyone is interested in just the Employee Directory, I can upload the current version to my Github.

Hi @elpinto007 Please Upload the stand-alone employee Directory i am looking for this only this solution as stadalone.

**Pull request merged**
