### PR TITLE
Added New e-mail and New meeting links at the top of the personal e-mail and personal calendar webparts

### LINKED ISSUE #163: New meeting button in upcoming meetings web part
I would love to see a new meeting button on top of the upcoming meeting web part which will open a new window with a new meeting dialog.

#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

### PR DESCRIPTION
**Pull request by Laskewitz**
Added New e-mail and New meeting links at the top of the personal e-mail and personal calendar webparts

#### Category
- [ ] Bug Fix
- [x] New Feature
- Related issues: fixes #163 #162 

#### What's in this Pull Request?

Added New e-mail and New meeting links at the top of the personal e-mail and personal calendar webparts.

### CODE REVIEW

**Comment by Laskewitz** [comment]
@eoverfield Added my PR again for the master branch

**Comment by VesaJuvonen** [comment]
Thanks Daniel, not quite sure on the comment related on @eoverfield and master branch, but like we state in the PR template we ONLY take contributions on the dev branch. This might be related on some different discussion, which we are not aware, but would need more input to ensure that we got this correct. Closing for now, but please submit this as a change to dev branch... so that we can get your contribution in.

**Comment by VesaJuvonen** [comment]
Actually - let me fix this right away so that we get this merged properly when we get the Starter Kit v1.3 released. So - updated PR to target to dev and merged now in. Thanks, Daniel, appreciated.

**Comment by VesaJuvonen** [comment]
Just realized that the guidance in the PR template was wrong, so sorry for that. Will be updated soon, already updated in the dev branch.

**Comment by eoverfield** [comment]
@Laskewitz I apologize for the confusion I caused. What @VesaJuvonen says is always the correct answer.

**Pull request merged**
