### PR TITLE
MS Graph Toolkit-based Personal Tasks Web Part

### PR DESCRIPTION
**Pull request by AJIXuMuK**
#### Category
- [ ] Bug Fix
- [x] New Feature
- Related issues: no

#### What's in this Pull Request?

MS Graph Toolkit-based Personal Tasks Web Part for v2

### CODE REVIEW

**Comment by eoverfield** [comment]
Thank you for the contribution, great example with Graph Toolkit.
Others have been adding their names to the solution authors list in the webpart's readme file, in case you want to update.

**Comment by AJIXuMuK** [comment]
@eoverfield I would include my name if I knew the original author of v1 web part - to include his name as well. Otherwise - it’s just the team.

**Comment by bcameron1231** [comment]
Hey @AJIXuMuK , Based on the history of the PersonalTasks Web Part in v1. The person who implemented the web part was Waldek!

**Comment by AJIXuMuK** [comment]
@bcameron1231 you were not so lazy as me ) I just looked at Readme file :) 
Will update the Readme

**Comment by bcameron1231** [comment]
Thanks Alex!!

**Pull request merged**
