### PR TITLE
[V2] Moving RecentlyVisitedSites webpart

### PR DESCRIPTION
**Pull request by YannickRe**
#### Category
- [X] New Feature

#### What's in this Pull Request?
- Moved V1 web part into V2 solution
- Included some pnp packages

### CODE REVIEW

**Comment by eoverfield** [comment]
Thank you for the PR, tested perfect.

Would you please update the readme to include past solution author(s), adding your name to the list, also merging over version history, adding a v2 line for this new "version", with a date of the latest PR date? Then make a PR and we will get that merged quickly.

Thanks!

**Comment by YannickRe** [comment]
@eoverfield Will do! Do I take the complete author list of the v1 starter kit or do I take only authors that committed on the specific web part?

**Comment by eoverfield** [comment]
Just the specific webpart please. Thanks.

**Comment by YannickRe** [comment]
I'll get there, I'm sure, but you've got any tips on how to "merge version history"? Seems like my GIT skills are lacking (or I'm completely misinterpreting and making it more difficult than it has to be, and you just mean to update the readme with previous authors)...

**Pull request merged**
