### PR TITLE
react-personal-contacts

### PR DESCRIPTION
**Pull request by vman**
#### Category
- [ ] Bug Fix
- [x] New Feature

#### What's in this Pull Request?

1. Moved the react-personal-contacts webpart to it's own solution
2. Updated the readme with Graph permissions requested by the webpart. Perhaps all webparts should have this.

### CODE REVIEW

**Comment by bcameron1231** [comment]
Thanks @vman ! Builds and works great!

Before I merge this in, can you make a couple updates for me?

Can you increase the version numbers inside the solution? 

1. Increase the Package.json to 2.0.0
2. Increase the package-solution to 2.0.0.0

As well as update the ReadMe file to include the previous author and release date for 1.0. Then  modify your record in the Version History to 2.0, and make sure the date is 2020 :)

We'd like to preserve from of the previous authors in the read me!

Thanks!

**Comment by vman** [comment]
Thanks @bcameron1231 , I have made the requested changes. 

Only thing is from where do I get the original author? This file doesn't have the info: https://github.com/SharePoint/sp-starter-kit/blob/master/documentation/components/wp-personal-contacts.md

Do we just look in the source history?

**Comment by bcameron1231** [comment]
Great! I usually pull the original from the history of the WebPart ts file. In this case, it's... 

waldekmastykarz - April 26th, 2018

Thanks again!

**Comment by bcameron1231** [comment]
Looks great! Thank you.

**Pull request merged**
