### PR TITLE
v1 collaboration footer extension to v2

### PR DESCRIPTION
**Pull request by spdavid**
#### Category
- [X] New Feature

**What's in this Pull Request?**
Moved v1 web part to v2 folder structure
Updated package to 2.0.0.0

### CODE REVIEW

**Comment by eoverfield** [comment]
@spdavid thank you for the PR.

In the readme, you reference that the user profile property is not available in onprem. I have been able to use the rest endpoint, /_api/SP.UserProfiles.PeopleManager/GetMyProperties to get custom profile properties in 2019. Is the issue how PnPJS handles this?

Also within readme, would you please update the Solution section to include the initial author as found via blame, and then add yourself. Within Versions, please make this version 2.0, and include the v1.0 release date, again from git.

The rest of the code is looking great, thank you again.

**Comment by eoverfield** [comment]
Also, would you consider adding more installation and utilization instructions in the Readme.md as this can now be installed independantly. I am thinking including PnP-Powershell to activate the extension with default property values. 

Also, what about updating elements.xml to include default properties as well?

**Comment by spdavid** [comment]
> @spdavid thank you for the PR.
> 
> In the readme, you reference that the user profile property is not available in onprem. I have been able to use the rest endpoint, /_api/SP.UserProfiles.PeopleManager/GetMyProperties to get custom profile properties in 2019. Is the issue how PnPJS handles this?
> 
> Also within readme, would you please update the Solution section to include the initial author as found via blame, and then add yourself. Within Versions, please make this version 2.0, and include the v1.0 release date, again from git.
> 
> The rest of the code is looking great, thank you again.

@eoverfield I do not have access to a SharePoint 2019 environment so its hard for me to test this at this point. The code is using the processQuery endpoint for retrieving the profile properties. So it should be ok. I'll update the readme regarding this. 

Ill fix the readme file with authors and versions.  Plus the steps to set up the custom user profile property. 

Also regarding the PowerShell. Currently the required list and taxonomy is included in the large provisioning file. I'm thinking it can be good to break this down into a smaller piece to install only the artifacts used for the webpart. So if people are only interested in this specific webpart it is easy to test.  Is there a strategy going forward for this regarding the whole solution?

**Comment by eoverfield** [comment]
I can assist with the SP 2019 testing and possible updates.

As for the documentation, we do not have guidelines yet. Suggestions and recommendations are always appreciated. If you have ideas here, please be the first and make a suggestion if you would. 

Long term we will need basic documentation on how to use the source for sure, yet for an extension when properties are required, specific solution driven documentation will be required in that particular solution's readme file.

**Comment by spdavid** [comment]
@eoverfield have now updated readme to provide some more guidance on the prerequisites.  Authors are updated.

**Comment by eoverfield** [comment]
Thanks for the contribution.

**Pull request merged**
