### PR TITLE
Fix Fabric 7 compiler errors in preparation of SPFx 1.10 upgrade

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Category
- [x] Bug Fix
- [ ] New Feature
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

This change-set incorporates the following fixes to unblock an eventual SPFx 1.10 upgrade:

- Fixes Fabric 7 related compiler errors:
    - Removes usage of `autobind` in favor of lambda functions to bind context, see https://github.com/OfficeDev/office-ui-fabric-react/commit/d7dd09998172855cfd005aa2ec901a575b838619.
    - Refactors usage of deprecated `TextField` `onChanged` to `onChange`, see [Fabric 7 release notes](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fabric-7).
    - Pins dependency `tslib@^1.10.0` for TSC 3.7 compatible for latest Fabric release, see https://github.com/OfficeDev/office-ui-fabric-react/pull/11739.
- Removes unused and redundant `@microsoft/rush-stack-compiler-2.7` devDep, see https://github.com/SharePoint/sp-starter-kit/commit/e5ffaf77d7772c2d2451c2ce9bad44e58a68bba1.
- IDE formatting for unformatted files

I'd like to upgrade to SPFx `1.10.0` in a separate PR. SPFx 1.9.1 brings-in Fabric 6 which supports these backwards-compatible changes. These changes will future-proof for Fabric 7.

### Before changes

```shell
Error - [tslint] node_modules/@microsoft/rush-stack-compiler-2.9/includes/tsconfig-base.json(12,5): error TS5023: Unknown compiler option 'declarationMap'.
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(12,3): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(138,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(150,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/collabFooter/CollabFooterApplicationCustomizer.ts(20,55): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/collabFooter/components/CollabFooter.tsx(10,95): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(12,3): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/Utilities"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(130,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(142,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(154,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(5,3): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(65,21): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/portalFooter/components/PortalFooter/PortalFooter.tsx(11,3): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/webparts/followedSites/components/FollowedSites.tsx(170,28): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(11,3): error TS2305: Module '"~/dev/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(194,25): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
```

### After changes

```shell
~\dev\sp-starter-kit\solution [keco/spfx-1dot10 ↑2 +0 ~1 -0 !]> gulp
Build target: DEBUG
[22:07:50] Using gulpfile ~\Work\sp-starter-kit\solution\gulpfile.js
[22:07:50] Starting gulp
[22:07:50] Starting 'default'...
[22:07:50] Starting subtask 'configure-sp-build-rig'...
[22:07:50] Finished subtask 'configure-sp-build-rig' after 5.43 ms
[22:07:50] Starting subtask 'pre-copy'...
[22:07:50] Finished subtask 'pre-copy' after 14 ms
[22:07:50] Starting subtask 'copy-static-assets'...
[22:07:50] Starting subtask 'sass'...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[22:07:51] Finished subtask 'sass' after 1 s
[22:07:51] Starting subtask 'tslint'...
[22:07:52] [tslint] tslint version: 5.12.1
[22:07:52] Starting subtask 'tsc'...
[22:07:52] [tsc] typescript version: 2.9.2
[22:07:52] Finished subtask 'copy-static-assets' after 2.16 s
[22:07:56] Finished subtask 'tslint' after 5.23 s
[22:07:59] Finished subtask 'tsc' after 7.55 s
[22:07:59] Starting subtask 'post-copy'...
[22:07:59] Finished subtask 'post-copy' after 307 μs
[22:07:59] Starting subtask 'collectLocalizedResources'...
[22:07:59] Finished subtask 'collectLocalizedResources' after 9.57 ms
[22:07:59] Starting subtask 'configure-webpack'...
[22:08:01] Finished subtask 'configure-webpack' after 1.84 s
[22:08:01] Starting subtask 'webpack'...
[22:08:23] Finished subtask 'webpack' after 21 s
[22:08:23] Starting subtask 'configure-webpack-external-bundling'...
[22:08:23] Finished subtask 'configure-webpack-external-bundling' after 606 μs
[22:08:23] Starting subtask 'copy-assets'...
[22:08:24] Finished subtask 'copy-assets' after 1.9 s
[22:08:24] Starting subtask 'write-manifests'...
[22:08:27] Finished subtask 'write-manifests' after 2.29 s
[22:08:27] Finished 'default' after 36 s
[22:08:27] ==================[ Finished ]==================
[22:08:28] Project sp-starter-kit version:1.5.4
[22:08:28] Build tools version:3.9.26
[22:08:28] Node version:v10.17.0
[22:08:28] Total duration:40 s
```

cc: @patmill @VesaJuvonen @johnguy0 @lahuey @dzearing

### CODE REVIEW

**Comment by KevinTCoughlin** [comment]
> Nit: Stylistically there are some things that bother me, e.g. wrapping return values with an extra paren. However, it's not a big deal.

I'm happy to revert those commits and intentionally kept them separate. That was my IDE enforcing _some_ style in code that was unstyled (incorrect indentation and such).

Regardless, thanks for review!

**Comment by johnguy0** [comment]
@KevinTCoughlin Please keep the style updates. I was just pointing that out. No need to change anything.

**Comment by eoverfield** [comment]
Thank you @KevinTCoughlin for the contribution, this has been merged into the master branch. There is an effort to copy and update all webpart/extensions in the current master version of this project to a V2 source, which may be reviewed via the V2 branch. We will look to include much of your updates in the split out source as well as soon as we can.

**Comment by KevinTCoughlin** [comment]
> Thank you @KevinTCoughlin for the contribution, this has been merged into the master branch. There is an effort to copy and update all webpart/extensions in the current master version of this project to a V2 source, which may be reviewed via the V2 branch. We will look to include much of your updates in the split out source as well as soon as we can.

Awesome, thanks @eoverfield! Feel free to tag me on those PRs. I wouldn't mind keeping tabs on the effort.

**Comment by VesaJuvonen** [comment]
Hi @KevinTCoughlin - as mentioned by @eoverfield, we are in progress of creating v2 Starter Kit and unfortunately your PR came to this in the worst possible time as we had not yet communicated this more widely and we did not yet align on this internally in engineering.

All of the web parts will be packaged on their own solution packages with the v2 release so that they can be also individually taken into use... this means that we have created already a new structure in following branch to which we would need now these changes to get updated as well -https://github.com/SharePoint/sp-starter-kit/tree/v2/source

This cannot be unfortunately automated, so it would be a manual thing. We can talk about this also in our engineering chats, if needed, but let's try to ensure that we get these changes also on the v2 side now that those structures were just finalized last week as well.

**Comment by KevinTCoughlin** [comment]
No worries @VesaJuvonen, I will take a look at porting the changes over to the above-linked branch today 😊.

**Comment by KevinTCoughlin** [comment]
I've raised the changes for `v2` branch in https://github.com/SharePoint/sp-starter-kit/pull/373.

**Pull request merged**
